# FreeBSD documentation
# $FreeBSD$

baseURL = "https://docs-dev.freebsd.org/"
title = "The FreeBSD Project"
copyright = "BSD 2-clause 'Simplified' License"
DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
disablePathToLower = true
theme = "beastie"
disableKinds = [ "taxonomy", "taxonomyTerm" ]
authors = [ "carlavilla@FreeBSD.org" ]
preserveTOC = true
ignoreFiles = [ "chapters-order.adoc$", "toc.adoc$", "toc-tables.adoc$", "toc-figures.adoc$", "toc-examples.adoc$", "toc-1.adoc$", "toc-2.adoc$", "toc-3.adoc$", "toc-4.adoc$", "toc-5.adoc$", "books.adoc$", "chapter.adoc$" ]

[markup.asciidocExt]
    preserveTOC = true

[outputs]
home = [ "HTML" ]
page = [ "HTML" ]
list = [ "HTML" ]
single = [ "HTML" ]
section = [ "HTML" ]
