# FreeBSD documentation
# $FreeBSD$

baseURL = "https://www-dev.FreeBSD.org/doc/"
title = "The FreeBSD Project"
copyright = "BSD 2-clause 'Simplified' License"
defaultContentLanguageInSubdir = true
disablePathToLower = true
theme = "beastie"
disableKinds = [ "taxonomy", "taxonomyTerm" ]
authors = [ "carlavilla@FreeBSD.org" ]
preserveTOC = true

[markup.asciidocExt]
    preserveTOC = true

[outputs]
home = [ "HTML" ]
page = [ "HTML" ]
list = [ "HTML" ]
single = [ "HTML" ]
section = [ "HTML" ]
